import { readCliPackageVersion } from './packageVersion.ts';

export function usage(): string {
  return [
    'evernote-obsidian — Evernote → Obsidian link repair',
    '',
    'Usage:',
    '  evernote-obsidian [--help|--version]',
    '  evernote-obsidian run --vault-dir <path> [--db <path>] [--snapshot <path>] [--map <path>] [--out <path>] [--map-out <path>] [--overrides <path>] [--max-notes <n>] [--json | --json-steps] [-q] [--progress] [--dry-run | --out-dir <path> | --in-place [--backup]]',
    '  evernote-obsidian index [--vault-dir <path>]',
    '  evernote-obsidian snapshot --db <path> [--out <path>] [--max-notes <n>]',
    '  evernote-obsidian links [--vault-dir <path>] [--out <path>] [--skip-other-evernote-hosts]',
    '  evernote-obsidian correlate --snapshot <path> [--vault-dir <path>] [--overrides <path>] [--out <path>] [--map-out <path>] [--report <path>] [--verbose]',
    '  evernote-obsidian guid-backfill --snapshot <path> [--vault-dir <path>] [--overrides <path>] [--dry-run | --in-place] [--report <path>] [--verbose]',
    '  evernote-obsidian rewrite --map <path> [--vault-dir <path>] [--dry-run | --out-dir <path> | --in-place [--backup]]',
    '  evernote-obsidian unescape-links [--vault-dir <path>] [--only <path>] [--dry-run | --out-dir <path> | --in-place [--backup]]',
    '  evernote-obsidian fix-resources [--vault-dir <path>] [--dry-run | --out-dir <path> | --in-place [--backup]]',
    '',
    'Commands:',
    '  run        Chain snapshot → correlate → unescape-links → rewrite → fix-resources (typical one-shot fix; --db unless --snapshot/--map reuse intermediates).',
    '  index      Build a read-only vault index (normalized titles must be unique).',
    '  snapshot   Export Evernote note metadata from an evernote-backup SQLite DB to JSON (not a vault snapshot).',
    '  links      Scan Markdown for Evernote note URLs and other evernote.com links (report only).',
    '  correlate  Join snapshot GUIDs to vault paths (evernote-guid frontmatter, else title); optional overrides JSON.',
    '  guid-backfill  Write missing evernote-guid frontmatter from a correlated snapshot (dry-run by default).',
    '  rewrite    Replace Evernote note URLs with Obsidian wikilinks using link-map.json from correlate.',
    '  unescape-links  Remove erroneous \\[…\\] wrappers around external [text](url) links from Evernote import.',
    '  fix-resources  Rewrite importer wikilinks Evernote/Writings/_resources/… → _resources/… (vault-fix; dry-run lists lines).',
    '',
    'Options:',
    '  --vault-dir                    Root directory of Markdown to scan (importer output, a subfolder, or full Obsidian vault; default: ./data)',
    '  --vault                        Alias for --vault-dir',
    '  --map                          Path to link map JSON (required for rewrite; on run, skips correlate and snapshot)',
    '  --dry-run                      Rewrite preview only (default when neither --out-dir nor --in-place)',
    '  --out-dir                      Write changed Markdown files under this directory (mirrors vault paths)',
    '  --in-place                     Overwrite Markdown in the vault (use with care)',
    '  --backup                       With --in-place, write <file>.evernote-obsidian.bak before overwriting',
    '  --snapshot                     Path to Evernote snapshot JSON (required for correlate)',
    '  --overrides                    Optional JSON file: { "version": 1, "byGuid": { "<guid>": "<path>" } }',
    '  --skip-other-evernote-hosts    Omit non-shard *.evernote.com URLs from the links report',
    '  --db                           Path to evernote-backup SQLite database (required for snapshot)',
    '  --out                          Output path (snapshot default: ./out/evernote-notes.json; correlate: ./out/link-map.json; links: stdout unless set)',
    '  --max-notes                    Stop after N notes (optional cap; notes ordered by title)',
    '  --snapshot-out                 Snapshot JSON output for run (alias: --out when generating a snapshot)',
    '',
    '  run defaults to a human-readable step summary on stdout when stdout is a TTY; otherwise (or with --json) it prints one JSON object with per-step summaries.',
    '  --json-steps restores the legacy behavior: one pretty-printed JSON blob per step on stdout.',
    '  --progress writes step progress lines to stderr (on by default for TTY runs). -q / --quiet with --json omits the extra "Run failed at …" line on stderr (human TTY output is unchanged).',
    '  With run, --map without --snapshot skips snapshot (and correlate); --db is ignored in that case.',
    '  --map-out                      Link map output for run (default: ./out/link-map.json)',
    '  --report                       On correlate failure, write full JSON detail here (default: ./out/correlate-report.json)',
    '  --verbose                      On correlate failure, also print full JSON detail on stderr (--report-stdout is an alias)',
    '  --only                         With unescape-links, limit to vault-relative path prefix (repeatable)',
    '  --skip-unescape-links          On run, omit the unescape-links step (Evernote URL rewrite only)',
    '',
    '  On correlate failure (exit 1), stderr shows a hint, vault/Evernote context, and next steps. Compact summary JSON is written when stderr is not a TTY (or with --json run output); use --verbose for full report JSON on stderr.',
    '  evernote-backup: https://github.com/vzhd1701/evernote-backup',
    '',
  ].join('\n');
}

export function cliVersion(): string {
  return readCliPackageVersion();
}
